<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTukpJUD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTukpJUD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTukpJUD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTukpJUD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTukpJUD\App_KernelDevDebugContainer([
    'container.build_hash' => 'TukpJUD',
    'container.build_id' => '3c4acc5a',
    'container.build_time' => 1727944754,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTukpJUD');
