<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJuYUuOY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJuYUuOY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJuYUuOY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJuYUuOY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJuYUuOY\App_KernelDevDebugContainer([
    'container.build_hash' => 'JuYUuOY',
    'container.build_id' => '49eb739d',
    'container.build_time' => 1727865082,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJuYUuOY');
